#!/usr/bin/env bash

# This monit wrapper script will be called by monit as root
# Edit these variables to your liking

RAILS_ENV=staging
RAILS_SERVE_STATIC_FILES=true
SECRET_KEY_BASE=c5d7282cb7a8840b60caec5746f277643554b5b6139d2ead4a8a359287e0519bc942b6fb74d5077f61f671df23b3a88967c6da6e58a7bbcfcf2a7907bdff4d13
RAILS_MAX_THREADS=5
WEB_CONCURRENCY=2
USER=web
APP_DIR=/srv/temple_staging/current
PUMA_CONFIG_FILE=$APP_DIR/config/puma.rb
PUMA_PID_FILE=/srv/temple_staging/shared/pids/puma.pid
PUMA_SOCKET=/srv/temple_staging/shared/pids/puma.sock

# check if puma process is running
puma_is_running() {
  if [ -S $PUMA_SOCKET ] ; then
    if [ -e $PUMA_PID_FILE ] ; then
      if cat $PUMA_PID_FILE | xargs pgrep -P > /dev/null ; then
        return 0
      else
        echo "No puma process found"
      fi
    else
      echo "No puma pid file found"
    fi
  else
    echo "No puma socket found"
  fi

  return 1
}

case "$1" in
  start)
    echo "Starting puma..."
    rm -f $PUMA_SOCKET

    echo "cd $APP_DIR && RAILS_MAX_THREADS=$RAILS_MAX_THREADS WEB_CONCURRENCY=$WEB_CONCURRENCY RAILS_SERVE_STATIC_FILES=$RAILS_SERVE_STATIC_FILES SECRET_KEY_BASE=$SECRET_KEY_BASE RAILS_ENV=$RAILS_ENV bundle exec puma -C $PUMA_CONFIG_FILE"
    /bin/su - $USER -c "cd $APP_DIR && RAILS_MAX_THREADS=$RAILS_MAX_THREADS WEB_CONCURRENCY=$WEB_CONCURRENCY RAILS_SERVE_STATIC_FILES=$RAILS_SERVE_STATIC_FILES SECRET_KEY_BASE=$SECRET_KEY_BASE RAILS_ENV=$RAILS_ENV bundle exec puma -C $PUMA_CONFIG_FILE"

    echo "done"
    ;;

  stop)
    echo "Stopping puma..."
      kill -s SIGTERM `cat $PUMA_PID_FILE`
      rm -f $PUMA_PID_FILE
      rm -f $PUMA_SOCKET

    echo "done"
    ;;

  restart)
    if puma_is_running ; then
      echo "Hot-restarting puma..."
      kill -s SIGUSR2 `cat $PUMA_PID_FILE`

      echo "Doublechecking the process restart..."
      sleep 15
      if puma_is_running ; then
        echo "done"
        exit 0
      else
        echo "Puma restart failed :/"
      fi
    fi
    ;;

  phased_restart)
    if puma_is_running ; then
      echo "Phased-restarting puma..."
      kill -s SIGUSR1 `cat $PUMA_PID_FILE`

      echo "Doublechecking the process restart..."
      sleep 10
      if puma_is_running ; then
        echo "done"
        exit 0
      else
        echo "Puma restart failed :/"
      fi
    fi
    ;;

  kill_worker*)
    if [ -z "$2" ];then
      logger -t "puma_${APP}" -s "kill_worker called with no worker identifier"
      exit 1
    fi
    PID_DIR=`dirname $PUMA_PID_FILE`
    kill -s QUIT `cat ${PID_DIR}/puma_worker_$2.pid`
    STATUS=$?
    exit $STATUS
    ;;

  *)
    echo "Usage: puma {start|stop|restart|kill_worker 0,1,2,etc}" >&2
    ;;
esac