subscription_plan = SubscriptionPlan.find_or_create_by(name: 'Temple | Molière - Abonnement 1€') do |subscription_plan|
  subscription_plan.position = 1
  subscription_plan.price_ati = 1.0
  subscription_plan.price_te = 0.83
  subscription_plan.taxes_rate = 20.0
  subscription_plan.displayable = false
  subscription_plan.favorite = false
  subscription_plan.commitment_period = 0
  subscription_plan.locations = ['moliere']
end

user_default_attributes = {
  password: 'abcd1234',
  password_confirmation: 'abcd1234',
  gender: 'M',
  street1: '1, temple street',
  postal_code: '75008',
  city: 'Paris',
  phone: '0102030405',
  birthdate: Date.current,
}

credit_card_default_attributes = {
  brand: 'bogus',
  number: '1111222233334444',
  expiration_month: 02,
  expiration_year: 2032,
  cvv: '123',
}

subscription_default_attributes = {
  subscription_plan_id: subscription_plan.id,
  commitment_period: subscription_plan.commitment_period,
  discount_period: 0,
  start_at: Date.current,
}

ghost_users = [
  {
    email: Settings.user.cash.email, 
    lastname: Settings.user.cash.lastname, 
    firstname: Settings.user.cash.firstname,
  },
  {
    email: Settings.user.cb.email, 
    lastname: Settings.user.cb.lastname, 
    firstname: Settings.user.cb.firstname,
  },
  {
    email: Settings.user.cheque.email, 
    lastname: Settings.user.cheque.lastname, 
    firstname: Settings.user.cheque.firstname,
  },
  {
    email: Settings.user.compensation.email, 
    lastname: Settings.user.compensation.lastname, 
    firstname: Settings.user.compensation.firstname,
  },
].each do |ghost_user_attrs|
  @user = ::User.where(email: ghost_user_attrs[:email]).first_or_create do |new_user|
    new_user.assign_attributes(ghost_user_attrs.merge(user_default_attributes))
  end
  if @user.persisted?
    @subscription = @user.subscriptions.first_or_create(subscription_default_attributes)
    if @subscription.persisted?
      @credit_card = @user.credit_cards.where(firstname: ghost_user_attrs[:firstname], lastname: ghost_user_attrs[:lastname]).first_or_create do |new_credit_card|
        new_credit_card.assign_attributes(
          {
            firstname: ghost_user_attrs[:firstname],
            lastname: ghost_user_attrs[:lastname],
          }.merge(credit_card_default_attributes)
        )
      end
      @subscription.start! if @credit_card.persisted? && @user.update_attributes({ current_credit_card_id: @credit_card.id, payment_mode: 'cb' })
    end
  end
end

ArticleCategory.find_or_create_by(name: "Droit d'accès")

#Slimpay member
if Rails.env.development?
  slimpay_users = [
    ["ROSALIE", "ABBEY"],
    ["ALIREZA", "ASHANI"],
    ["ALEXANDRE", "ABOULKER"],
    ["MATTEO",  "AGOSTINO"],
    ["VICTORIA",  "ANFUSO"],
    ["VICTOR",  "ARFI"],
    ["LAURENT", "BELLEC"],
    ["RAPHAEL", "BENHAMOU"],
    ["STEPHAN", "BERNARD"],
    ["PIERRE",  "BESSON"],
    ["VINCENT", "BLANCHARD"],
    ["CANDICE", "BLOIS"],
    ["VALERIE", "BIRON"],
    ["ALICE", "BLOND"],
    ["ALEXIS",  "BOTAYA"],
    ["MAXIME",  "BOURE"],
    ["MOHAMED-ZAKI","BOUSLIKHANE"],
    ["NICOLAS", "BOUTTIER"],
    ["THIBAULT",  "BRACCIO"],
    ["GAEL",  "BRILLANT"],
    ["THOMAS",  "BUICANGES"],
    ["TOMASZ",  "BRONIEK-PONIATOUSKI"],
    ["FRANCOIS",  "BUHAGIAR"],
    ["CHRISTOPHE",  "CARPENTIER"],
    ["CARLA", "CABALFIN"],
    ["FLORIAN", "CADIER"],
    ["AUDE",  "CATRICE"],
    ["ALICE", "CHARRAS"],
    ["ANTOINE", "CHEVREAU"],
    ["CHRISTOPHE",  "BOURASSEAU"],
    ["JEROME",  "CHEVY"],
    ["ANTON", "CHYRKOV"],
    ["ANTONY",  "COHEN"],
    ["FABIEN",  "COHEN"],
    ["HADRIEN", "COLMANT-RICHARD"],
    ["THIERRY", "CONSTANT"],
    ["FOULQUES",  "DE JOURDAN"],
    ["ETIENNE", "DE LACHADENEDE"],
    ["CHRISTOPHE",  "DELFOUR"],
    ["GREGORY", "DEMULE-THENON"],
    ["CECILE",  "DE ROSA"],
    ["LOUIS-CHARLES","DESTIEVAN"],
    ["SIBY",  "DIABIRA"],
    ["WILLIAM", "DONNERS"],
    ["FRANCK",  "DRAY"],
    ["NICOLAS", "DUMOND"],
    ["CHARLES", "DURAND"],
    ["ADAM",  "ELKHAIAT"],
    ["ARNAUD",  "ESQUEVIN"],
    ["THIBAUD", "FARALDO"],
    ["EMMANUEL",  "FOISSOTTE"],
    ["HUGUES",  "FERRIERE"],
    ["ROMAIN",  "FILET"],
    ["STEFANO", "FIORINI"],
    ["ARNAUD",  "FORTIN"],
    ["OLIVIER", "FRETTE DAMICOURT"],
    ["ANDREA",  "FURIAMOTTO"],
    ["FRANCOIS",  "GALTIE"],
    ["ELENIO",  "GABBANELLI"],
    ["CLEMENT", "GAMBERONI"],
    ["VINCENT", "GARIBALDI"],
    ["CHARLES-EDOUARD","GARNIER"],
    ["MARIE FREDERIQUE", "GAS"],
    ["HUGUES",  "GASCON"],
    ["ARNAUD",  "GENSAC"],
    ["ALEXANDRE",   "GERVAIS"],
    ["BENOIT",  "GRANEL"],
    ["MAXIME",  "GOUSSARD"],
    ["JIMMY", "GROSS"],
    ["FRANCOIS",  "GOIZE"],
    ["FAHD AL MONTASSIR", "JAMAI"],
    ["STANISLAS", "JAMOIS"],
    ["KONSTANTIN",  "GUETCHEVSKI"],
    ["BRUNO", "HERNANDEZ BARRERA"],
    ["MATTHIEU",  "HUG"],
    ["SOPHIE",  "HUGUES"],
    ["NICOLAS", "IBANEZ"],
    ["TONY",  "JACOB"],
    ["OLIVIER", "JACQUEMART"],
    ["STEPHANE",  "JACQUEMIN"],
    ["KHALIF",  "IBRAHIM"],
    ["GABRIEL", "KARABOULAD"],
    ["JORDAN",  "KOJA"],
    ["OLIVIER", "LABBE"],
    ["BENJAMIN",  "LAIDET"],
    ["ADRIEN",  "LE BAIL"],
    ["ESTELLE", "LEBAR"],
    ["GAEL",  "LEIBLANG"],
    ["HUGO",  "LE MORVAN"],
    ["ALEXIS",  "LEVY"],
    ["RAPHAEL", "LEGRAND"],
    ["FEGLIENS",  "LONDAS"],
    ["IVAN",  "LUNG"],
    ["GUILLAUME", "MACLOUF"],
    ["BENJAMIN",  "MAHE"],
    ["SEBASTIEN", "MALHERNE"],
    ["MEHDI", "MARJANI"],
    ["ALISTAIR",  "MARCA"],
    ["JEAN-BAPTISTE","MARCAIS"],
    ["GILLES",  "MARTINEAU"],
    ["ERIC",  "MARTINET"],
    ["BENEDICTE", "MALLET"],
    ["THIERRY", "MARX"],
    [  "SAS", "MONIN"],
    ["AMAURY",  "MESCLON"],
    ["BRICE", "MORVENT"],
    ["CAROLINE",  "MOURGUIART"],
    ["RITA",  "MOUAWAD"],
    ["RUBEN", "NATAF"],
    ["ANDRES",  "NAVARRO"],
    ["VLADIMIR",  "NAZARYAN"],
    ["PIERRE",  "NOEL"],
    ["MELANIE", "PEDRO"],
    ["RACHEL",  "PERRICHOT"],
    ["CLEMENTINE",  "PIAZZA"],
    ["YOAN",  "POCHET"],
    ["JULIETTE",  "PLOQUIN"],
    ["JENNIFER",  "QUINETTE"],
    ["MATHILDE",  "RETIF"],
    ["STEPHANE",  "RETTERER MASPERO"],
    ["THIBAUT", "RICHARD"],
    ["ERICK", "ROCA"],
    ["CESAR", "RODRIGUEZ MONTES"],
    ["GREGOIRE",  "ROSSI"],
    ["ALEXIS",  "SARRAZIN"],
    ["MARGAUX", "SAVY"],
    ["BENJAMIN",  "SINNASSAMY"],
    ["SOPHIE",  "THIENOT"],
    ["SANDRINE",  "TONYE"],
    ["GUILLAUME", "SALMON"],
    ["ALEXANDRE",   "SCHOULER"],
    ["CHRISTOPHE",  "SAINTON"],
    ["FRANCK",  "SILBERS-MOORE"],
    ["THIERRY", "SCHWOB"],
    ["ALEXANDRE",   "SIMON"],
    ["THAOTHONG", "SARANUPHONG"],
    ["THOMAS",  "HUGUES"],
    ["LILIA", "TORCHANI"],
    ["JEAN-BAPTISTE","TRISTRAM"],
    ["NOEL",  "VALLIERE"],
    ["CLAUDIO", "VANDI"],
    ["TRISTAN", "VOISIN"],
    ["JULIEN",  "VELU"],
    ["ROKHAYA", "DIALLO"],
    ["RAUL",  "SHIMABUKU LANDAURE"],
    ["LOUIS", "BIZOUARD DE MONTILLE"],
    ["DIMITRI", "ABOULKER"],
    ["LILIA", "AFIA"],
    ["EMILIE",  "ALEXANDRE"],
    ["HENRI", "ALMERAS"],
    ["MARC",  "ALVADO"],
    ["ROMAIN",  "ALTCHE"],
    ["STEPHANE",  "AMBERG"],
    ["PAUL",  "ANCELE"],
    ["EMMANUELLE",  "ARIN"],
    ["ANGELO",  "ASSE"],
    ["MARCO", "ARLAUD"],
    ["ARAM",  "ATTAR-HAMEDANI"],
    ["MARC-ANTOINE","AVON"],
    ["OLIVIA",  "BAES"],
    ["KAREL", "BALAS"],
    ["CHLOE", "BARTHELEMY"],
    ["THIBAULT",  "BASQUIN"],
    ["AURELIEN",  "BESSAHLI"],
    ["NICOLAS", "BESSOLES"],
    ["MARIE",   "BEAUCHAUD"],
    ["LAURENT", "BEAUQUESNE"],
    ["AMAURY",  "BLANLOEIL"],
    ["MARIE-HELENE","MUNOZ"],
    ["STEPHANE",  "BENOUAICH"],
    ["NICOLAS", "BEYRET"],
    ["CEDRIC",  "BONNET"],
    ["MARGAUX", "BOIVIN IVARS"],
    ["SARAH", "BOUALEM"],
    ["REDOUANE",  "BOUGHERABA"],
    ["MATHIEU", "BIDAL"],
    ["MATHIEU", "BIGAND"],
    ["FREDERIC",  "BOUSQUET"],
    ["MARC",  "BREBANT"],
    ["NICOLAS", "BRIEC"],
    ["MATTHIEU",  "BROCHIER"],
    ["DAVID", "BRY"],
    ["PHILIPPE",  "CADI "],
    ["TSIRITANTELY",  "CAHN"],
    ["FABIEN",  "CALIXTE"],
    ["DAVIDE",  "CALVARUSO"],
    ["ROMAIN",  "CAYLA"],
    ["ISABELLE",  "CAYLA"],
    ["MORGANE", "CAYLA"],
    ["GABRIEL", "CAYROL"],
    ["JULIE", "CECCALDI"],
    ["CAMILLE", "CHAAL"],
    ["EUNICE",  "CHAMMAS"],
    ["CAROLINE",  "CHANCE"],
    ["THOMAS",  "CHANDAT"],
    ["FREDERIC",  "CHICHE"],
    ["THOMAS",  "COLIN"],
    ["CHRISTOPHE",  "COMBES"],
    ["AGATHE",  "COUDERC"],
    ["ARNAUD",  "CORNETTE DE SAINT CYR"],
    ["CHARLES", "ALAIN COUSIN"],
    ["EMMANUELLE",  "COSTE"],
    ["JEAN-MATHIEU","COT"],
    ["CHARLES", "COVILLE"],
    ["LIONEL",  "CUDEY"],
    ["D'HAESE","ADRIEN"],
    ["DALBERTO",  "DAMIEN"],
    ["CLEMENT", "PICHOT DE CHAMPFLEURY"],
    ["ROBIN", "DAUZON"],
    ["MATTHIAS",  "DARRACQ"],
    ["FRANCOIS",  "DEBENEY"],
    ["FRANCK",  "DELBES"],
    ["LORRAINE",  "DENIS"],
    ["LAMBERT", "DEMANGE"],
    ["ALBAN", "DE MARIGNAN"],
    ["THEODORE",  "DESHAYES"],
    ["LOUIS-CHARLES","DESTIEVAN"],
    ["DIANE", "DIBO"],
    ["LUGIAN",  "DING"],
    ["DANIELE", "DI RUZZA"],
    ["FLORENCE",  "DUBOIS"],
    ["ARNAUD",  "DUCRET"],
    ["MAXIME",  "DUGAST"],
    ["NATHALIE",  "DUGAUD"],
    ["MARINE",  "DUPUIS"],
    ["GUILLAUME", "DUPRE"],
    ["SOPHIE",  "DUTERTRE"],
    ["BENJAMIN",  "DUVAL"],
    ["ALEXANDRA", "CRESCITZ DUVERGER"],
    ["AYMERIC", "EROUART"],
    ["ARMAND",  "EZERZER"],
    ["FANNY", "EUZET"],
    ["LOUIS-JEAN","EL GAMMAL"],
    ["DEYAE", "EL OTMANI"],
    ["EMMANUELLE",  "FARHAT"],
    ["SERGE", "FAUBERT"],
    ["ELIE",  "FAYE"],
    ["DOROTHEE",  "FERTE"],
    ["MARIE-SOLENE","FERTE"],
    ["GUILLAUME", "FEKKAI"],
    ["MATHIAS", "FISCH"],
    ["SADIK", "FILIPOVIC"],
    ["CEDRIC",  "FLORES"],
    ["FRANCESCO", "FONZARI"],
    ["AUDE",  "FRAIOLI-MARCAL"],
    ["SOFIA", "FRAYSSINET-RODRIGUES"],
    ["JEREMIE", "FREIBURGER"],
    ["JONATHAN",  "GALBRUN"],
    ["MANON", "GALLICIAN"],
    ["LOUIS", "GANSER"],
    ["PASCAL",  "GARBARINI"],
    ["CAMILLE", "GARCIN"],
    ["CAROLINE",  "GAIMARI"],
    ["CHARLES-EDOUARD","GARNIER"],
    ["CLARISSE",  "GARNIER"],
    ["DARIA", "GASPARRONI"],
    ["THIERRY", "GAUTHIER-DELMAS"],
    ["ROMAIN",  "GAVACHE"],
    ["ELODIE",  "GAZEAU"],
    ["YVES",  "GENOUVRIER"],
    ["CLEMENT", "GHYS"],
    ["GILLES",  "GIUDICELLI"],
    ["JULIEN",  "GORGE"],
    ["FRANCOIS-XAVIER","GOLDSMITH"],
    ["JOAQUIM", "GONCALVES"],
    ["ULYSSE",  "GRALL"],
    ["GILLES",  "GIUDICELLI"],
    ["ADRIEN",  "GUILLEMIN"],
    ["STANISLAS", "GULCZYNSKI"],
    ["VINCENT", "GRANIER"],
    ["JOELLE",  "HARB"],
    ["ORIANE",  "HAZANE"],
    ["PHILIPPE",  "HERTANU"],
    ["NIMA", "AMIR HAERI"],
    ["FRANK", "HORT"],
    ["BERTRAND",  "HAAS"],
    ["GREGOIRE",  "HERVET"],
    ["FREDERIC",  "HERVO"],
    ["THOMAS",  "HOLLANDE"],
    ["STEPHANE",  "HYPOLITE"],
    ["JEAN PHILIPPE ET OLIVIER", "HUGOT HUGOTAVOCATS"],
    ["BRUNO", "IGNACE"],
    ["XAVIER",  "JACQUET"],
    ["AURORE",  "JAUGIN"],
    ["YOANN", "JEGOUX"],
    ["GUILLAUME",   "JEANNET"],
    [  "JONDEAU", "PRO"],
    ["FLORIAN", "KAHN"],
    ["ELZBIETA",  "KARASINSKA"],
    ["MICHAEL", "KHAYAT"],
    ["AXEL",  "KIENER"],
    ["LIONEL",  "KLEIN"],
    ["THOMAS",  "KOEGLER"],
    ["ARNAUD",  "KOLB"],
    ["STEPHANE",  "KOVACS"],
    ["HALINA",  "KOZLECKA"],
    ["RAPHAELLE", "LACHAUME"],
    ["JEREMIE", "KRIEF"],
    ["ROMAIN",  "LAMBERT"],
    ["AUDREY",  "LANDON"],
    ["GREGORY", "LASSUS-DEBAT"],
    ["ANDREEA", "LATU"],
    ["THIBAULT",  "LAUPRETRE"],
    ["MARC",  "LEBEL"],
    ["PAUL",  "LEFEUVRE"],
    ["CLEMENT JULES GERARD", "LECOINTRE"],
    ["DAVID", "LELIEF"],
    ["ELODIE",  "LELIEF"],
    ["CLAIRE",  "LEMAITRE"],
    ["PIERRE", "YVES LESAGE"],
    ["ADRIEN",  "LEVINGER"],
    ["ALAIN", "LEVY"],
    ["CHARLES", "LEVY"],
    ["ARTHUR",  "LIMINANA"],
    ["LUCAS", "LIMONNE"],
    ["JEREMY",  "LOPES"],
    ["JONATHAN",  "LOPES"],
    ["GAELLE",  "LORIN"],
    ["NICOLAS", "LOVAS"],
    ["ISILE", "LUTTMANN"],
    ["ESTELLE", "MANIPOUD"],
    ["CAMILLE", "MAURICE"],
    ["THOMAS",  "MEAULLE"],
    ["YACINE",  "MERAD BOUDIA"],
    ["ISADORA", "DE FRITAS MACIEL"],
    ["SARAH", "MADI"],
    ["ARTHUR",  "MALLET"],
    ["GABRIEL", "MAUGER"],
    ["ARNAUD",  "M BEMBA"],
    ["CHRISDELE", "M BEMBA"],
    ["SEBASTIEN", "MARCILLAC"],
    ["DIDIER",  "MARTINEZ"],
    ["VICTOR",  "MENDRAS"],
    ["ANATOLE", "MEYLAN"],
    ["DAVID", "MINGOT"],
    ["AMELIE",  "MOLINSKI"],
    ["LAURE",   "MONSET"],
    ["ROXANE",  "MOREAU"],
    ["ALEXANDRA", "MOULLE-BERTEAUX"],
    ["ROMAIN",  "MULLER"],
    ["MUSTAPHA",  "NAJMI"],
    ["SOFIA", "NEBIOLO"],
    ["MOAD",  "NEFATI"],
    ["GUILLAUME", "NGUYEN CONG DUC"],
    ["ROMAIN",  "NOEL"],
    ["ANTOINE", "PEZET"],
    ["TINSINA", "ONG"],
    ["GABRIEL", "PHILIPPE"],
    ["JEAN-CLEMENT","PIERRE"],
    ["ALEXANDRE",   "MARTIN-ROSSET"],
    ["SANDRINE",  "MOUCHET"],
    ["PATRICK", "MILLE"],
    ["AMELIE",  "MOURRAIN"],
    ["EMMANUEL",  "NAHMIAS"],
    ["NATHALIE",  "NERON"],
    ["RAPHAEL", "NUGERON"],
    ["DOMINIQUE", "NUYTENS"],
    ["CHRISTINE", "ORTOLANO"],
    ["YASSIN",  "OUTASSOU"],
    ["FRANCESCA", "PARISE"],
    ["AUGUSTIN",  "PAUL PETIT"],
    ["MAUD",  "PETIT"],
    ["LOUIS-AMAURY","PELISSIER"],
    ["ERIC",  "PERRET"],
    ["HELENE",  "PERRIN"],
    ["ISABELLE",  "PERRON"],
    ["CHARLES", "PERONNIN"],
    ["EMMANUELLE",  "PEUCH"],
    ["SOPHIE",  "PEYROUTET"],
    ["SERGE", "PIERRARD"],
    ["GERALDINE", "POLGE"],
    ["ARTHUR",  "PORRE"],
    ["PATRICK", "PFUNDSTEIN"],
    ["MARIE AIMEE", "PIRIOU"],
    ["AYMERIC", "POULAIN"],
    ["CECILE",  "PUDEBAT"],
    ["ION", "RAILEAN"],
    ["VINCENT", "RAFIS"],
    ["DIA",   "RAMATA KANI"],
    ["CATHERINE", "PELOUX"],
    ["RAOUL", "TACHON"],
    ["ROMAN", "RIBEMON"],
    ["ANTOINE", "ROBICHON"],
    ["GUILLAUME", "ROLLAND"],
    ["THOMAS",  "ROULLAND"],
    ["CHRISTOPHE",  "JOVER"],
    ["ALAIN", "RUELLO"],
    ["NICOLAT", "RUGGIERI"],
    ["RICHARD", "SAINT ETIENNE"],
    ["FELIX", "ROUX"],
    ["ARYA",  "SALAHSHOUR"],
    ["GARANCE",   "SAMUEL LA JEUNESSE"],
    ["FRANCESCU", "SANTONI"],
    ["ELISE", "SAUVINET"],
    ["HUGO",  "SANTROT"],
    ["FRANCOIS-CHARLES"," SCAPULA"],
    ["JESSIKA", "SCHLOSSER"],
    ["INGRID",  "SCHMITTER"],
    ["ELIE",  "SEBBAG"],
    ["GERALDINE", "SENNEUR"],
    ["JUSTINE", "SIDORSKI"],
    ["FILIPA",  "SILVANO"],
    ["MARIE", "SLAVICEK"],
    ["JULIEN",  "SULZER"],
    ["ALEXANDRA", "TAGNATI"],
    ["RUDY",  "TASIMOVICZ"],
    ["MAIA",  "TCHERNIAKOVA"],
    ["FREDERIC",  "TENGELMANN"],
    ["THIL",  "ABEILLE"],
    ["CHARLES-ANTOINE", "THOMAS"],
    ["CHARLES", "TOUBOUL"],
    ["JEAN JACQUES", "THIBERT"],
    ["MTCC","test"],
    ["ANNE",  "KERAMBRUN"],
    ["MARION",  "VACHER"],
    ["ALEXANDRE",   "VAYSSE"],
    ["GILLES",  "VEDRENNE"],
    ["GREG",  "VEDRENNE"],
    ["THIBAULT",  "VANPEENE"],
    ["EDOUARD", "VERROUST"],
    ["CAROLE",  "VERGEZ LEONARDO"],
    ["ORSO",  "VESPERINI"],
    ["ANTHONY", "VIBERT"],
    ["SEBASTIEN", "VIEILLEDENT"],
    ["DAVID", "WANG"],
    ["JULIEN",  "VILLEMONTEIX"],
    ["GEORGES", "WAZEN"],
    ["OLIVIER", "WICKER"],
    ["BASTIEN", "WILSHAW"],
    ["LESLEY",  "WOOD"],
    ["LARA",  "YAHIA"],
    ["MYRIAM",  "YAHIA"],
    ["PIERRE-GUIVE","YAZDANI"],
    ["YOON",  "SE-RIN"],
    ["MARLONE", "ZARD"],
    ["KATARZYNA", "ZARZEKA"],
    ["PIERRE-MAXIME","ZENATI"],
    ["ANTOINE", "ZUCCHET"],
    ["FABRICE",   "STAAD"],
    ["JORDAN",  "BALTAZE"],
    ["STEPHANE",  "BODELOT"],
    ["MARC-ANDREA","BOUQUIN"],
    ["PAUL",  "CHAIGNON"],
    ["MATHIEU", "CLEACH"],
    ["VITOR", "LOPES CENTODUCATTE"],
    ["FABIEN",  "DUPONCEL"],
    ["BRICE", "LAFONT"],
    ["ENGUERRAN", "LAVAUD"],
    ["AURELIE",   "MONBET"],
    ["EMMANUEL",  "POIRIER D\'ORSAY"],
    ["OCTAVIO", "URTIZ"],
    ["JAMES ROBERT", "WILLIAM"],
    ["TRISTAN", "GROIX"],
    ["CLEMENT", "GAMBERONI"],
    ["MORGANE", "RIVOAL"],
    ["SANDRA",  "TOSELLO"],
    ["LOUISON", "HARDY"],
    ["AYMERIC", "RAVET"],
    ["EUGENIE", "SCHWOB"]
  ]
  slimpay_credit_card_firstname = Settings.user.cash.firstname
  slimpay_credit_card_lastname = Settings.user.cash.lastname

  slimpay_users.each do |user|
    @user = ::User.where(firstname: user[0], lastname: user[1]).first_or_create do |new_user|
      new_user.assign_attributes({
        email: "slimpay_#{rand(99999999999999999999999999)}_#{rand(99)}@test.com",
        firstname: user[0],
        lastname: user[1],
      }.merge(user_default_attributes))
    end 
    @subscription = @user.subscriptions.first_or_create(subscription_default_attributes)
    if @subscription.persisted?
      @credit_card = @user.credit_cards.where(firstname: slimpay_credit_card_firstname, lastname: slimpay_credit_card_lastname).first_or_create do |new_credit_card|
        new_credit_card.assign_attributes(
          {
            firstname: slimpay_credit_card_firstname,
            lastname: slimpay_credit_card_lastname,
          }.merge(credit_card_default_attributes)
        )
        end
      @subscription.start! if @credit_card.persisted? && @user.update_attributes({ current_credit_card_id: @credit_card.id, payment_mode: 'cb' })
    end
  end
end
